apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: front
    version: v2
  name: front
  namespace: dhcims-msapoc-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
        version: v2
    spec:
      containers:
      - env:
        - name: TZ
          value: Asia/Shanghai
        image: docker-registry.default.svc:5000/dhcims-msapoc-dev/front:183
        imagePullPolicy: Always
        name: front
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 600m
            memory: 1536Mi
          requests:
            cpu: 200m
            memory: 512Mi
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: front-config
          subPath: default.conf
        - mountPath: /etc/opt/rh/rh-nginx112/nginx/nginx.conf
          name: nginx-config
          subPath: nginx.conf
      volumes:
      - configMap:
          items:
          - key: front-config
            path: default.conf
          name: front-config
        name: front-config
      - configMap:
          items:
          - key: nginx.conf
            path: nginx.conf
          name: nginx-config
        name: nginx-config