apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: front
    version: v2
  name: front
  namespace: dhcims-msapoc-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
        version: v2
    spec:
      containers:
      - env:
        - name: TZ
          value: Asia/Shanghai
        image: <image-name>
        imagePullPolicy: Always
        name: front
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 600m
            memory: 1536Mi
          requests:
            cpu: 200m
            memory: 512Mi
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: nginx-config
          subPath: default.conf
      volumes:
      - configMap:
          items:
          - key: front-config
            path: default.conf
          name: front-config
        name: nginx-config