apiVersion: v1
kind: ConfigMap
metadata:
  name: front-config
  namespace: dhcims-msapoc-dev
data:
  front-config: |-
    # gzip设置
    gzip on;
    gzip_vary on;

    gzip_comp_level 6;
    gzip_buffers 16 8k;

    gzip_min_length 1000;
    gzip_proxied any;
    gzip_disable "msie6";
    #gzip_http_version 1.0;
    gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript;

    server {
        listen       8080;
        server_name  localhost;
        root   /usr/share/nginx/html;

        #charset koi8-r;
        #access_log  /var/log/nginx/host.access.log  main;

        location ~* \.(html|js|css|jpg|png|woff|ttf)$ {
            index  index.html index.htm;
            root   /usr/share/nginx/html;
        }


        location = /{
            index  index.html index.htm;
            root   /usr/share/nginx/html;
        }

        
        location /{
                proxy_pass http://gateway:8080;
                index  index.html index.htm;
                proxy_http_version 1.1;
                #proxy_set_header Host $host;
                #proxy_set_header X-Real-IP $remote_addr;
                #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

    }